### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kotomei** [kotomei/fcm-for-mojo#1]
因为很渣，所以第一版只是能跑起来，更具体的修改还需要继续摸索 Docker 的工作模式和使用方法

- [x] 当 `FFM.pm` 推送至上游时对 Dockerfile 进行微调
- [x] ~~可以在 Docker 内部保存 http-auth 文件~~ 使用 ENV 解决
- [x] 可以保留对 `config.json` 的修改

**Comment by simonsmh** [comment]
perl版本在安装时没有指定啊，更新了咋办

**Comment by kotomei** [comment]
首先我需要能知道获取 Perl 版本并声明变量的方法（
到时候肯定需要完善
~~但是现阶段又不是不能用~~

**Comment by WordlessEcho** [comment]
感觉……这样搞得好像 docker 完全无法实现的样子……

**Comment by simonsmh** [comment]
> 保留对 config.json 的修改

需要用到 [挂载](https://docs.docker.com/engine/reference/builder/#volume) 么
我有点担心，如果它跑在没有提供额外空间的docker服务上会出现什么

**Comment by simonsmh** [comment]
> perl版本在安装时没有指定啊，更新了咋办

/etc/perl

**Comment by simonsmh** [comment]
> 可以在 Docker 内部保存 http-auth 文件

不如从ENV读取

**Comment by simonsmh** [comment]
- [ ] 重写readme

**Comment by simonsmh** [comment]
- [ ] 缩减docker体积
一个镜像要几百兆，还是有点大过头了

**Comment by simonsmh** [comment]
- [ ] 服务端按上游进度及时构建更新
可以考虑Ci或者Webhook

**Comment by lxltyw** [comment]
WARNING: apt does not have a stable CLI interface. Use with cautio
 in scripts.
创建时提示这个

**Comment by simonsmh** [comment]
@lxltyw 这很正常啊，等着就好了

**Comment by simonsmh** [comment]
490MB -> 149MB
切换到alpine，体积减小了很多

**Comment by lxltyw** [comment]
等着没反应啊，然后就中断连接了

**Comment by simonsmh** [comment]
@lxltyw 之前是拿debian镜像做的，等待时间长真的是因为需要安装依赖。我刚刚改了一个基于alpine的Dockerfile，请试试看。

**Comment by lxltyw** [comment]
root@jdu4e00u53f7:~/docker# docker build -t kotomeinyan/fcm-for-mo
o .
Sending build context to Docker daemon  6.656kB
Step 1/17 : FROM debian:stretch
 ---> a20fd0d59cf1
Step 2/17 : LABEL maintainer "kotomei <i@kotomei.moe>"
 ---> Using cache
 ---> 254aece9adac
Step 3/17 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 078fb8053927
Step 4/17 : ENV USER rikka PASSWD rikka
 ---> Using cache
 ---> 4be94865b212
Step 5/17 : EXPOSE 5005
 ---> Using cache
 ---> 2f7069018743
Step 6/17 : RUN apt update -qq && apt install -yqq wget gnupg
 ---> Running in f61a40b45fdf

WARNING: apt does not have a stable CLI interface. Use with cautio
 in scripts.


连接中断

**Comment by simonsmh** [comment]
**Dockerfile更新了**，我刚刚改了一个基于alpine的Dockerfile，请试试看。
另外，帮助你守护进程的软件，诸如screen或者tmux，不妨一试。

**Comment by kotomei** [comment]
#6

**Comment by kotomei** [comment]
t
